[package]
name = "resolver"
version = "0.1.0"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log        = "0.4"
bitflags   = "1.2"
punycode   = "0.4"
base64     = "0.10"
openssl    = "0.10"
native-tls = "0.2"
lru        = "0.3"
mio        = { version = "0.6", optional = true }

[features]
default  = [ "mio" ]
nightly  = [ ]
vendored = [ "openssl/vendored" ]
